/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    AppCart: typeof import('./views/AppCart/index.vue')['default']
    AppDetail: typeof import('./views/AppDetail/index.vue')['default']
    AppList: typeof import('./views/AppList/index.vue')['default']
    AppLogin: typeof import('./views/AppLogin/index.vue')['default']
    AppMain: typeof import('./views/AppMain/index.vue')['default']
    AppMainBanner: typeof import('./views/AppMain/AppMainBanner/index.vue')['default']
    AppMainNavList: typeof import('./views/AppMain/AppMainNavList/index.vue')['default']
    AppMine: typeof import('./views/AppMine/index.vue')['default']
    AppNotFound: typeof import('./views/AppNotFound/index.vue')['default']
    AppRegister: typeof import('./views/AppRegister/index.vue')['default']
    CommonFooter: typeof import('./components/CommonFooter/index.vue')['default']
    CommonHeader: typeof import('./components/CommonHeader/index.vue')['default']
    CommonList: typeof import('./components/CommonList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSearch: typeof import('vant/es')['Search']
    VanSpace: typeof import('vant/es')['Space']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
  }
}
